apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openai-DM-Mobile
  annotations:
    github.com/project-slug: codeiain/openai-DM-Mobile
spec:
  type: other
  system: openai-DM
  lifecycle: unknown
  owner: staff
  consumesApis: 
    - openai-DM-Auth-Service
