apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openai-DM-Mobile
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: codeiain/openai-DM-Mobile
spec:
  type: website
  system: openai-dm-mobile
  lifecycle: experimental
  owner: staff
  consumesApis: 
    - openai-dm-auth-api
    - openai-dm-web-socket-api
