---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openai-dm
  # annotations:
  #   backstage.io/techdocs-ref: dir:.
  #   github.com/project-slug: codeiain/openai-DM-character-service
spec:
  owner: iain
---
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openai-DM-Mobile
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: codeiain/openai-DM-Mobile
spec:
  type: website
  system: openai-dm
  lifecycle: experimental
  owner: iain
  consumesApis: 
    - openai-dm-auth-api
    - openai-dm-web-socket-api
